### ISSUE TITLE
highlighted text colour is too light or maybe transparent to be identify

### ISSUE THREAD

**Issue by hrdkmishra** [decaycs/vscode#1]
![image](https://user-images.githubusercontent.com/87580981/170858808-e4eee3f1-4e8e-433d-9625-154fb3dabe08.png)

i cant confirm whether its is selected or not but just seeing , make it more vivid so it could stand out.

maybe something like this ->
![image](https://user-images.githubusercontent.com/87580981/170858947-81ad97c4-18d4-47a6-aff6-5671bbaae396.png)

and i really liked the theme.

thanks

**Comment by AlphaTechnolog** [comment]
well, looks like a good idea, i'll try to get this for the next version! and thank you for the feedback!
